spring.application.name=demo
spring.web.resources.static-locations=classpath:/static/,classpath:/public/

spring.datasource.url=jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Seoul
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 보안 파일 연동 설정 추가
spring.config.import=optional:application-secret.properties